name: GitHub Metrics

on:
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: prashillonakar

          # ðŸ”¥ THIS IS REQUIRED
          filename: github-metrics.svg
          output_action: commit

          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: true
          config_octicon: true
          config_timezone: Asia/Kolkata
          config_twemoji: true

          plugin_languages: true
          plugin_languages_indepth: true
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%

          plugin_leetcode: true
          plugin_leetcode_user: prashillonakar

          committer_message: "ðŸ“ˆ Update GitHub metrics [skip ci]"
