name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories, activity, community
          repositories_forks: no
          repositories_affiliations: owner
          activity_limit: 5
          activity_days: 14
          repositories_order: stars

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 6

          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_sort: stars

          plugin_code: yes
          plugin_code_lines: 12
          plugin_code_load: 400

