name: GitHub Metrics

on:
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      issues: read
      pull-requests: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Fix Docker installation conflicts
        run: |
          sudo apt-get remove -y containerd docker.io containerd.io
          sudo apt-get update
          sudo apt-get install -y docker.io jq

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: prashillonakar
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: true
          config_octicon: true
          config_timezone: Asia/Kolkata
          config_twemoji: true

          plugin_languages: true
          plugin_languages_indepth: true
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%

          plugin_leetcode: true
          plugin_leetcode_user: prashillonakar

          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: main
          committer_message: "ðŸ“ˆ Update GitHub metrics [skip ci]"
